dist: xenial

language: python
python:
  - '3.7'

services:
  - docker

matrix:
  fast_finish: true
  include:

    - name: "Test"
      stage: test
      install: true
      script: ./scripts/test.sh

    - name: "Release"
      stage: deploy
      install: pip3 install -q --upgrade twine
      script: ./scripts/upload.sh
      # release only if tag like #.#.#
      if: (tag =~ ^[0-9]+(\.[0-9]+){2}$)
