version: "2.1"

services:

  # ---------------------------------
  # Aether Kafka Containers
  # ---------------------------------

  zookeeper-test:
    image: confluentinc/cp-zookeeper:5.5.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - moby:127.0.0.1

  kafka-test:
    image: confluentinc/cp-kafka:5.5.1
    links:
      - zookeeper-test
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-test:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-test:29092
      ADVERTISED_HOST_NAME: kafka-test
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_URL: ${KAFKA_URL}
      SECURITY.PROTOCOL: ${KAFKA_SECURITY}
      SASL.MECHANISM: PLAIN
      SASL.USERNAME: ${KAFKA_CONSUMER_USER}
      SASL.PASSWORD: ${KAFKA_CONSUMER_PASSWORD}
    ports:
      - 29092:29092
    extra_hosts:
      - moby:127.0.0.1

  redis-test:
    image: redis:alpine


  # ---------------------------------
  # Aether Consumer SDK
  # ---------------------------------

  consumer-test:
    build: .
    env_file:
      - tests/test_environment.env
    volumes:
      - .:/code
