version: "2.1"

services:

  # ---------------------------------
  # Aether Kafka Containers
  # ---------------------------------

  redis-test:
    image: redis:3-alpine
    command: [
      "--requirepass", "${REDIS_PASSWORD:-aredispassword}",
      "--notify-keyspace-events", "KA",
      "--appendonly", "yes"
    ]
    env_file:
      - tests/test_environment.env
    ports:
      - 6379:6379

  zookeeper-test:
    image: confluentinc/cp-zookeeper:5.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - moby:127.0.0.1

  kafka-test:
    image: confluentinc/cp-kafka:5.2.1
    links:
      - zookeeper-test
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-test:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-test:29092
      ADVERTISED_HOST_NAME: kafka-test
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 29092:29092
    extra_hosts:
      - moby:127.0.0.1

  # ---------------------------------
  # Aether Consumer SDK
  # ---------------------------------

  consumer-test:
    build: .
    env_file:
      - tests/test_environment.env
    volumes:
      - .:/code
