version: "3.7"

services:

  # ---------------------------------
  # Aether Kafka Containers
  # ---------------------------------

  zookeeper-test:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-test:
    image: confluentinc/cp-kafka:latest
    links:
      - zookeeper-test
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-test:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-test:29092
      ADVERTISED_HOST_NAME: kafka-test
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis-test:
    image: redis:alpine


  # ---------------------------------
  # Aether Consumer SDK
  # ---------------------------------

  consumer-test:
    build: .
    env_file:
      - tests/test_environment.env
    volumes:
      - .:/code
